version: '3.8'

services:
  web:
    # This is the path to the Dockerfile for the service. We use . because the Dockerfile for our web service can be found in the same folder as our docker-compose.yml file.
    build: .
    # This is were we map the port from the container with our host computer. Our web service will be running on port 3000.
    env_file:
      - .env    
    ports:
      - "3000:3000"
    depends_on:
      - db  
    volumes:
    # Where . is the host directory, and /usr/src/app is the target directory for the containers.
      - .:/usr/src/app
    command: go run cmd/main.go

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
# The path to the actual volume is handled by docker internals.
volumes:
  postgres-db: